[theme]
base                     = "light"
primaryColor             = "#FD951F"
backgroundColor          = "#FFFFFF"
secondaryBackgroundColor = "#F4F4F6"
textColor                = "#1A1A2E"
font                     = "sans serif"